spring.application.name=todoList
spring:
  application:
    name: todo-list

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Moscow

server:
  port: 8080

logging:
  level:
    com.example.todolist: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG